server:
  port: ${PORT:8090}

spring:
  application:
    name: client

endpoints:
  health:
    enabled: true
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

home-service:
  host: localhost:8080