server:
  port: ${PORT:8080}

spring:
  application:
    name: service
    instance_id: ${random.value}

endpoints:
  health:
    enabled: true
    sensitive: true
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false